<?php
/**
 * @var Klevu\Recommendations\Block\Html\Head\ThemeV2\AddPriceSuffixToQuery $block
 * @var Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php
$scriptStringChains = "
    klevu.settings.chains.initChain.add({
        name: 'addPriceSuffixToRecsQuery',
        fire: function (data) {
            if (klevu.getObjectPath(klevu.recs, 'base', false)
                && klevu.getGlobalSetting('flags.addPriceSuffixToQuery.recsModule', false)
                && typeof klevu_addPriceSuffixToQueryControl === 'object'
            ) {
                klevu.search.base.getScope().chains.request.control.addAfter('initRequest', klevu_addPriceSuffixToQueryControl);
                klevu.setObjectPath(data, 'flags.addPriceSuffixToQuery.recsModule', false);
            }
        }
    });
    ";
?>
<?php
$recsPowerUp = "
    klevu({ powerUp: { recsModule: true } });
";

$recsPowerUpWithSuffix = "
    klevu({
        powerUp: { recsModule: true },
        flags: {
            addPriceSuffixToQuery: {
                recsModule: true
            }
        }
    });
";
?>
<?php if ($block->isDeferJs()): ?>
    <?php
    $scriptString = "
        window._klvReady = window._klvReady || [];
        window._klvReady.push(function() {
            {$scriptStringChains}
        });

        var klevuPowerUpRecs = function() {
            window._klvReady = window._klvReady || [];
            window._klvReady.push(function() {
                klevu.support.hook(['magento.customRecs'], function() {
                    {$recsPowerUp}
                });
            });

            return true;
        };
        var klevuPowerUpRecsWithSuffix = function () {
            window._klvReady = window._klvReady || [];
            window._klvReady.push(function() {
                klevu.support.hook(['magento.customRecs'], function() {
                    {$recsPowerUpWithSuffix}
                });
            });

            return true;
        };
    ";
        ?>
<?php else: ?>
    <?php
    $scriptString = "
        {$scriptStringChains}

        var klevuPowerUpRecs = function() {
            {$recsPowerUp}

            return true;
        };
        var klevuPowerUpRecsWithSuffix = function () {
            {$recsPowerUpWithSuffix}

            return true;
        };
    ";
    ?>
<?php endif; ?>
<?php
$scriptString .= "
    document.addEventListener('{$block->getCustomerDataLoadErrorEventName()}', function () {
        klevuPowerUpRecs();
    });
    document.addEventListener('{$block->getCustomerDataLoadedEventName()}', function () {
        klevuPowerUpRecsWithSuffix();
    });
";
?>
<?= $secureRenderer->renderTag(
    'script',
    [
        'type' => 'text/javascript',
        'id' => 'klevu_recs_pricesuffix',
    ],
    $scriptString,
    false
) ?>

