<?php
/**
 * @var Klevu\Recommendations\Block\Html\Head\ThemeV2\AddPriceSuffixToQuery $block
 * @var Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php
$scriptString = <<<script
    klevu.settings.chains.initChain.add({
        name: "addPriceSuffixToRecsQuery",
        fire: function (data) {
            if (klevu.getObjectPath(klevu.recs, "base", false)
                && klevu.getGlobalSetting("flags.addPriceSuffixToQuery.recsModule", false)
                && typeof klevu_addPriceSuffixToQueryControl === "object"
            ) {
                klevu.search.base.getScope().chains.request.control.addAfter('initRequest', klevu_addPriceSuffixToQueryControl);
                klevu.setObjectPath(data, "flags.addPriceSuffixToQuery.recsModule", false);
            }
        }
    });

    document.addEventListener('{$block->getCustomerDataLoadErrorEventName()}', function () {
        klevu({ powerUp: { recsModule: true }});
    });
    document.addEventListener('{$block->getCustomerDataLoadedEventName()}', function () {
        klevu({
            powerUp: {
                recsModule: true
            },
            flags: {
                addPriceSuffixToQuery: {
                    recsModule: true
                }
            }
        });
    });
script;
?>
<?= $secureRenderer->renderTag(
    'script',
    ['type' => 'text/javascript'],
    $scriptString,
    false
) ?>

